// GENERATED by tools/langs.mjs from the vendored model files. Do not edit.
// `bytes` is the exact size of the gzipped file the browser downloads.

export interface Language {
  code: string;
  name: string;
  bytes: number;
}

export const LANGUAGES: Language[] = [
  { code: 'nld', name: 'Dutch', bytes: 10218699 },
  { code: 'eng', name: 'English', bytes: 10923060 },
  { code: 'fra', name: 'French', bytes: 6279601 },
  { code: 'deu', name: 'German', bytes: 7101284 },
  { code: 'pol', name: 'Polish', bytes: 8365004 },
  { code: 'spa', name: 'Spanish', bytes: 8362819 },
];
