/**
 * The OCR result's Pro action: save a searchable PDF. Present only in a Pro-flag build, and only
 * acts for someone signed in (src/pro/gate.ts); otherwise it says what the feature is and where to
 * sign in, and does nothing else.
 *
 * A file whose pages all gave their text from their own text layer is searchable already. That is
 * said first, before the account is mentioned: there is nothing to gain, so no reason to ask. The
 * offer once appeared for such a file, saved a re-saved copy with nothing added, and said "2 of 2
 * pages are now searchable".
 *
 * The result sentence switches to "now searchable" only after a file has actually been written,
 * and it is generated by describeSearchable from the writer's own count of pages it layered. The
 * free path's sentence (src/lib/ocr-result.ts) cannot say "searchable" at all.
 */
import { writeSearchable, describeSearchable, searchableMark, pagesToLayer, type SearchablePage } from './searchable.js';
import { signedIn, signInPrompt } from './gate.js';
import { saveFile } from '../lib/ui.js';
import { suffixName } from '../lib/format.js';

export interface SearchableOffer {
  fileName: string;
  sourceBytes: Uint8Array;
  pages: SearchablePage[];
  scaleFor: (index: number) => number;
  counts: { pagesRead: number; pageCount: number; fromLayer: number };
  /** Called with the regenerated result sentence once the file has been written. */
  onWritten: (said: { head: string; announce: string }) => void;
}

export function offerSearchable(host: HTMLElement, o: SearchableOffer): void {
  host.textContent = '';
  host.dataset.pdfiqPro = searchableMark();

  // Nothing was read, so there is no layer to write — said rather than left blank. An empty slot
  // where a Pro offer belongs reads as a feature that is missing, not as one with nothing to do
  // (check 28). Found by opening the page with a document OCR could read nothing from.
  if (!o.counts.pagesRead) {
    const nothing = document.createElement('p');
    nothing.className = 'hint';
    nothing.textContent =
      'No text was read from this document, so there is nothing to write into a searchable copy: '
      + 'the layer is made from the words that were recognised, and there were none.';
    host.append(nothing);
    return;
  }

  if (!pagesToLayer(o.pages)) {
    const already = document.createElement('p');
    already.className = 'hint';
    already.textContent = o.counts.fromLayer === o.counts.pageCount
      ? 'Every page of this file has its own text layer, so it is searchable already. A searchable copy would add nothing.'
      : 'The pages that gave text already had their own text layer, so they are searchable already; the rest are named above. ' +
        'A searchable copy would add nothing.';
    host.append(already);
    return;
  }

  if (!signedIn()) {
    host.append(signInPrompt('A searchable PDF'));
    return;
  }

  const button = document.createElement('button');
  button.type = 'button';
  button.className = 'btn-quiet';
  button.textContent = 'Save as a searchable PDF';
  const hint = document.createElement('p');
  hint.className = 'hint';
  hint.textContent =
    'Adds the recognised words to the PDF as an invisible layer, so the file itself can be searched ' +
    'and copied from. The scan is not changed, and it is written here, on this device.';

  button.onclick = async () => {
    button.disabled = true;
    button.textContent = 'Writing the text layer…';
    try {
      const { bytes, layered } = await writeSearchable(o.sourceBytes, o.pages, o.scaleFor);
      // Worded before saving: describeSearchable refuses a copy that layered no page, and then
      // nothing is handed over under a sentence that says otherwise.
      const said = describeSearchable({ pageCount: o.counts.pageCount, fromLayer: o.counts.fromLayer, layered });
      saveFile(bytes, suffixName(o.fileName, '-searchable'));
      o.onWritten(said);
      button.textContent = 'Save the searchable PDF again';
    } catch (err) {
      button.textContent = 'Save as a searchable PDF';
      hint.textContent = `The text layer could not be written: ${err instanceof Error ? err.message : String(err)}. ` +
        'The text above is unaffected.';
    } finally {
      button.disabled = false;
    }
  };

  host.append(button, hint);
}
