/**
 * The OCR result's Pro action: save a searchable PDF. Present only in a Pro-flag build, and only
 * acts for someone signed in (src/pro/gate.ts); otherwise it says what the feature is and where to
 * sign in, and does nothing else.
 *
 * A file whose pages all gave their text from their own text layer is searchable already. That is
 * said first, before the account is mentioned: there is nothing to gain, so no reason to ask. The
 * offer once appeared for such a file, saved a re-saved copy with nothing added, and said "2 of 2
 * pages are now searchable".
 *
 * The result sentence switches to "now searchable" only after a file has actually been written,
 * and it is generated by describeSearchable from the writer's own count of pages it layered. The
 * free path's sentence (src/lib/ocr-result.ts) cannot say "searchable" at all.
 */
import { writeSearchable, describeSearchable, searchableMark, pagesToLayer, type SearchablePage } from './searchable.js';
import { proAccount, lockedPanel, lockControls } from './gate.js';
import { saveFile } from '../lib/ui.js';
import { suffixName } from '../lib/format.js';

export interface SearchableOffer {
  fileName: string;
  sourceBytes: Uint8Array;
  pages: SearchablePage[];
  scaleFor: (index: number) => number;
  counts: { pagesRead: number; pageCount: number; fromLayer: number };
  /** The file as chosen, for Unlock to carry to the checkout and back. */
  source?: () => File | null;
  /**
   * Called once the file has been written, with the regenerated result sentence and the copy
   * itself — the page has a PDF of its own making to offer onward only from this moment.
   */
  onWritten: (said: { head: string; announce: string }, copy: { bytes: Uint8Array; name: string }) => void;
}

/**
 * The options step, before any reading: whether this browser can use the searchable PDF. Before this the
 * feature was invisible until a run finished, and not always then (reported four times). Said in words about
 * what the person can do.
 */
export function introSearchable(host: HTMLElement, source?: () => File | null): void {
  host.dataset.pdfiqPro = searchableMark();
  host.textContent = '';
  if (proAccount()) {
    // Owned: no word of Pro, only what will happen (owner, 13 September 2026: after buying, the site stops selling).
    host.append('Saving it as a searchable PDF is offered with the text, once reading finishes.');
    return;
  }
  // The card around this already says what it does, and the real button does not exist before reading, so there is
  // nothing to show locked here: the action only (approved copy, 13 September 2026).
  host.append(lockedPanel('searchable', 'The searchable PDF', source, { noWhat: true, noInstead: true }));
}

/** A plain card headed "Searchable PDF", for every answer that is not the locked panel (which has its own heading). */
function plainCard(host: HTMLElement, ...children: Node[]): void {
  const card = document.createElement('div');
  card.className = 'card';
  const kicker = document.createElement('p');
  kicker.className = 'kicker';
  kicker.textContent = 'Searchable PDF';
  card.append(kicker, ...children);
  host.append(card);
}

export function offerSearchable(host: HTMLElement, o: SearchableOffer): void {
  host.textContent = '';
  host.dataset.pdfiqPro = searchableMark();

  // Nothing was read, so there is no layer to write — said rather than left blank. An empty slot
  // where a Pro offer belongs reads as a feature that is missing, not as one with nothing to do
  // (check 28). Found by opening the page with a document OCR could read nothing from.
  if (!o.counts.pagesRead) {
    const nothing = document.createElement('p');
    nothing.className = 'hint';
    nothing.textContent =
      'No text was read from this document, so there is nothing to write into a searchable copy: '
      + 'the layer is made from the words that were recognised, and there were none.';
    plainCard(host, nothing);
    return;
  }

  if (!pagesToLayer(o.pages)) {
    const already = document.createElement('p');
    already.className = 'hint';
    already.textContent = o.counts.fromLayer === o.counts.pageCount
      ? 'Every page of this file has its own text layer, so it is searchable already. A searchable copy would add nothing.'
      : 'The pages that gave text already had their own text layer, so they are searchable already; the rest are named above. ' +
        'A searchable copy would add nothing.';
    plainCard(host, already);
    return;
  }

  const button = document.createElement('button');
  button.type = 'button';
  button.className = 'btn-quiet';
  button.textContent = 'Save as a searchable PDF';

  // Not owned: the real button, locked, then the words (approved copy, 13 September 2026). No handler is attached.
  if (!proAccount()) {
    const locked = document.createElement('p');
    locked.style.margin = '0';
    locked.append(button);
    lockControls(locked);
    host.append(lockedPanel('searchable', 'A searchable PDF', o.source, { title: 'Searchable PDF', controls: locked }));
    return;
  }
  const hint = document.createElement('p');
  hint.className = 'hint';
  hint.textContent =
    'Adds the recognised words to the PDF as an invisible layer, so the file itself can be searched ' +
    'and copied from. The scan is not changed, and it is written here, on this device.';

  button.onclick = async () => {
    if (!proAccount()) return;
    button.disabled = true;
    button.textContent = 'Writing the text layer…';
    try {
      const { bytes, layered } = await writeSearchable(o.sourceBytes, o.pages, o.scaleFor);
      // Worded before saving: describeSearchable refuses a copy that layered no page, and then
      // nothing is handed over under a sentence that says otherwise.
      const said = describeSearchable({ pageCount: o.counts.pageCount, fromLayer: o.counts.fromLayer, layered });
      const name = suffixName(o.fileName, '-searchable');
      saveFile(bytes, name);
      o.onWritten(said, { bytes, name });
      button.textContent = 'Save the searchable PDF again';
    } catch (err) {
      button.textContent = 'Save as a searchable PDF';
      hint.textContent = `The text layer could not be written: ${err instanceof Error ? err.message : String(err)}. ` +
        'The text above is unaffected.';
    } finally {
      button.disabled = false;
    }
  };

  const row = document.createElement('p');
  row.style.margin = '10px 0 0';
  row.append(button);
  plainCard(host, row, hint);
}
