/**
 * The index at the top of CLAIMS.md, generated from the checks below it.
 *
 * CLAUDE.md used to open with "CLAIMS.md holds 18 checks". It held 27. The number had been
 * right once and was maintained by hand beside a file that only grows, which is check 18
 * applied to the sentence introducing check 18 — a stale claim with a scheduled failure date.
 *
 * A hand-maintained count with a guard is still a hand-maintained count. So there is no count
 * written down anywhere now: this generates the index from the headings, and `--check` fails
 * the build when what is on disk disagrees with what the headings say. CLAUDE.md points at
 * the file and states no number at all.
 *
 * Numbering is verified as contiguous from 1 as a side effect, which is the mistake actually
 * available when appending to a 27-entry list at the end of a long session.
 *
 *   node tools/claims-index.mjs           rewrite the index
 *   node tools/claims-index.mjs --check   fail if it is out of date (prebuild)
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const FILE = join(ROOT, 'CLAIMS.md');
const OPEN = '<!-- index: generated by tools/claims-index.mjs — do not edit by hand -->';
const CLOSE = '<!-- /index -->';

const slug = (t) =>
  t.toLowerCase().replace(/[^\w\s-]/g, '').trim().replace(/\s/g, '-');

function build(src) {
  const checks = [...src.matchAll(/^### (\d+)\. (.+)$/gm)].map((m) => ({
    n: Number(m[1]),
    title: m[2].trim(),
  }));
  if (!checks.length) throw new Error('CLAIMS.md has no numbered checks — the index would be empty');

  checks.forEach((c, i) => {
    if (c.n !== i + 1) {
      throw new Error(
        `CLAIMS.md numbering jumps: check ${i + 1} is written as ${c.n} ("${c.title}").\n` +
        `Renumber so the list runs 1..${checks.length} without gaps or repeats.`
      );
    }
  });

  const anchors = new Map();
  for (const c of checks) {
    const a = `${c.n}-${slug(c.title)}`;
    if (anchors.has(a)) throw new Error(`two checks share the anchor #${a}`);
    anchors.set(a, c);
  }
  const lines = checks.map((c) => `${c.n}. [${c.title}](#${c.n}-${slug(c.title)})`);
  return { checks, block: `${OPEN}\n\n${lines.join('  \n')}\n\n${CLOSE}` };
}

function splice(src, block) {
  const i = src.indexOf(OPEN);
  if (i === -1) {
    // First run: put it under the "## The checklist" heading it indexes.
    const at = src.indexOf('## The checklist');
    if (at === -1) throw new Error('CLAIMS.md has no "## The checklist" heading to index');
    const end = at + '## The checklist'.length;
    return src.slice(0, end) + '\n\n' + block + src.slice(end);
  }
  const j = src.indexOf(CLOSE, i);
  if (j === -1) throw new Error('CLAIMS.md has an index opening marker with no closing one');
  return src.slice(0, i) + block + src.slice(j + CLOSE.length);
}

const src = readFileSync(FILE, 'utf8');
let checks, next;
try {
  const built = build(src);
  checks = built.checks;
  next = splice(src, built.block);
} catch (e) {
  // A numbering gap is a normal editing mistake, not a crash. Say so and stop.
  console.error(`
CLAIMS.md: ${e.message}
`);
  process.exit(1);
}

if (process.argv.includes('--check')) {
  if (next !== src) {
    console.error(
      '\nCLAIMS.md index is out of date. Run:\n\n  node tools/claims-index.mjs\n\n' +
      `(${checks.length} checks found in the headings.)\n`
    );
    process.exitCode = 1;
  } else {
    console.log(`claims index: ${checks.length} checks, numbering contiguous, index current`);
  }
} else {
  writeFileSync(FILE, next);
  console.log(`claims index: wrote ${checks.length} entries`);
}
